models:
  - provider: chutes
    model: unsloth/gemma-3-12b-it
    temperature: 0.2
    seed: 42
  - provider: chutes
    model: zai-org/GLM-4.5-FP8
    temperature: 0.2
    seed: 42
  - provider: chutes
    model: zai-org/GLM-4.5-Air
    temperature: 0.2
    seed: 42
